---
- name: Copy Docker Compose file
  copy:
    src: ../../../../docker-compose-callme.yml
    dest: /home/ec2-user/docker-compose.yml

- name: Start Docker service from the Compose file
  become: true
  command: docker stack deploy -c /home/ec2-user/docker-compose.yml callme
