---
- name: Copy Docker Compose file
  copy:
    src: ../../../../docker-compose-callme.yml
    dest: /home/ec2-user/docker-compose.yml

- name: Start Docker services from the Compose file
  become: true
  command: docker-compose -f /home/ec2-user/docker-compose.yml up -d
