version: '3'
services:
  callme:
    image:
    networks:
      - mynetwork 
    ports:
      - "80:8000"
    environment:
      - DJANGO_ALLOWED_HOSTS={{ host_ip }}
    restart: unless-stopped
    hostname: callme

networks:
  mynetwork: