---
- name: Update all packages
  yum:
    name: '*'
    state: latest
    update_only: yes

- name: Search for Docker package
  yum:
    list: docker
  register: docker_package

- name: Install Docker
  yum:
    name: docker
    state: present
  register: docker_install_result
  ignore_errors: yes

- name: Add user to the docker group
  user:
    name: ec2-user
    groups: docker
    append: yes

- name: Reload user's group assignments
  command: newgrp docker
  become: true
  become_user: ec2-user

- name: Install Python 3 pip
  yum:
    name: python3-pip
    state: present

- name: Install Docker Compose
  pip:
    name: docker-compose
    executable: pip3

- name: Enable Docker service at startup
  service:
    name: docker
    state: started
    enabled: yes
