---
- name: Update package cache
  yum:
    name: '*'
    state: latest
    update_cache: yes

- name: Upgrade all packages
  yum:
    name: '*'
    state: latest
    update_cache: yes
    security: yes
