AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  DefaultVpc:
    Type: String
    Description: Default VPC
  FirstSubnet:
    Type: String
    Description: first subnet

Resources:
  EC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: ami-0c94855ba95c71c99 
      VpcId: !Ref DefaultVpc
      InstanceType: t2.micro
      KeyName: my-key-pair
      SecurityGroupIds:
        - !Ref EC2SecurityGroup
      SubnetId: !Ref FirstSubnet
      Tags:
        - Key: Name
          Value: MyEC2Instance

  ElasticIP:
    Type: 'AWS::EC2::EIP'
    Properties:
      InstanceId: !Ref EC2Instance

  IPAssociation:
    Type: 'AWS::EC2::EIPAssociation'
    Properties:
      AllocationId: !GetAtt ElasticIP.AllocationId
      NetworkInterfaceId: !GetAtt EC2Instance.NetworkInterfaces[0].Ref

  EC2SecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Security group for EC2 instance
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
      VpcId: !Ref 'AWS::AccountId'

