AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  DefaultVpc:
    Type: String
    Description: Default VPC
  FirstSubnet:
    Type: String
    Description: first subnet

Resources:

  MyKeyPair2:
    Type: 'AWS::EC2::KeyPair'
    Properties:
      KeyName: MyKeyPair2

  EC2Instance2:
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: ami-0f1a6835595fb9246
      InstanceType: t2.micro
      KeyName: !Ref MyKeyPair2
      SecurityGroupIds:
        - !Ref EC2SecurityGroup2
      SubnetId: !Ref FirstSubnet
      Tags:
        - Key: Name
          Value: MyEC2Instance

  ElasticIP2:
    Type: 'AWS::EC2::EIP'
    Properties:
      InstanceId: !Ref EC2Instance2

  IPAssociation2:
    Type: 'AWS::EC2::EIPAssociation'
    Properties:
      AllocationId: !GetAtt ElasticIP2.AllocationId
      InstanceId: !Ref EC2Instance2

  EC2SecurityGroup2:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Security group for EC2 instance
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
      VpcId: !Ref DefaultVpc

  MyECRRepository2:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: callme
      RepositoryPolicyText:
        Version: "2012-10-17"
        Statement:
          - Sid: AllowPushPull
            Effect: Allow
            Principal: "*"
            Action:
              - ecr:GetDownloadUrlForLayer
              - ecr:BatchGetImage
              - ecr:BatchCheckLayerAvailability
              - ecr:PutImage
              - ecr:InitiateLayerUpload
              - ecr:UploadLayerPart
              - ecr:CompleteLayerUpload
              - ecr:DescribeRepositories
              - ecr:GetRepositoryPolicy
              - ecr:ListImages
              - ecr:DeleteRepository
              - ecr:DeleteRepositoryPolicy
              - ecr:SetRepositoryPolicy

Outputs:
  KeyNameOutput:
    Value: !Ref MyKeyPair2

  ElasticIP:
    Value: !GetAtt ElasticIP2.PublicIp

  ECRRepositoryARN:
    Value: !Ref MyECRRepository
    Description: The ARN of the ECR repository